### ISSUE TITLE
Why menu item may be not available?

### ISSUE THREAD

**Issue by LeusMaximus** [leecade/caniuse_local#2]
Why menu item may be not available?
http://prntscr.com/3cw4v2

**Comment by leecade** [comment]
sorry for that, because I picked a wrong name for package name.

I send a new PR to fixed it: 

https://github.com/wbond/package_control_channel/pull/3153

You can try it now:

remove it, and clone it into your package folder, ensure this plugin's folder name is `caniuse`

**Comment by LeusMaximus** [comment]
Maybe I'm doing something wrong, but menu item is available now, but it isn't working

**Comment by leecade** [comment]
plugin's folder name is `caniuse`?

**Comment by leecade** [comment]
ensure this plugin's folder name is `caniuse`, restart sublime editor (if required)

**Comment by LeusMaximus** [comment]
It seems to be working. Thanks.

**Comment by LeusMaximus** [comment]
If I understand correctly, the properties that are supported by all browsers are not displayed? (for example  relative  or   absolute...)
And only shows the last few versions of browsers?

**Comment by leecade** [comment]
Soon you'll be able to install by `Package Control`.

Is mainly used for display css3 / html5 / canvas...., please see: http://caniuse.com/

I made an adapter to supports css prop / js API, for example:

`-webkit-white-space` = `white-space` = `CSS3 tab-size`
